### PR TITLE
feat: upgrade SD-JWT package

### PR DESCRIPTION
**Pull request by lukasjhan**
Hi, This PR is for applying new version of SD JWT package.
I'm developing SD JWT package in https://github.com/openwallet-foundation-labs/sd-jwt-js.

This is my first time contributing to SSI-SDK, but I plan to continue contributing with SD-JWT.
If there is anything you want to change, please feel free to let me know and I will fix it. :)

FYI: I'm going to make a PR to PEX as soon as this issue: https://github.com/openwallet-foundation-labs/sd-jwt-js/issues/132 is resolved. 

And might take some time because I should look more closely at the PEX source code to understand how they works.
If you have any documentation for me to understand, please let me know.

Thank you.

### CODE REVIEW

**Review by nklomp — APPROVED** [review]
LGTM thanks.

After some initial confusion about the npm package being the same, but the maintainer and Github being different and no mention of @berendsliedrecht in the README, nor in the commit history from last year, I found out that apparently the two libs have been merged.

**Comment by nklomp** [comment]
I will wait however to merge this, given PEX is using @sphereon/ssi-types and potentially might be using some of the functions exposed here (not sure from the top of my head)

**Comment by lukasjhan** [comment]
> LGTM thanks.
> 
> After some initial confusion about the npm package being the same, but the maintainer and Github being different and no mention of @berendsliedrecht in the README, nor in the commit history from last year, I found out that apparently the two libs have been merged.

Sorry I was forgot to mention it. Two lib have been merged as you said. :)

**Comment by nklomp** [comment]
Yes that foe sure has our pref. I did notice it, but was okay with it because of the name changes of some methods it seems.

Given I will wait with merging until pex has the same version, I rather would see a patch, minor or major release instead of an unstable version

**Comment by lukasjhan** [comment]
> @lukasjhan maybe we make a `latest` release at sd-jwt-js before linking here a next version? I think then it's easier here to see if we got updates since we are giving the version like `^0.3.3` or so.

Yeah, I'll change the package version as soon as we released. Let's merge it after that :)

**Comment by lukasjhan** [comment]
Hi, Can you guys deploy openid4vci and openid4vp-siop as well After PEX is ready please?

btw: I'm currently working on PEX :)

**Comment by lukasjhan** [comment]
Hi @nklomp, I opened a PR in PEX: https://github.com/Sphereon-Opensource/PEX/pull/144
And I also sd-jwt package version in this PR as well.

**Review by nklomp — APPROVED** [review]

**Pull request merged**
