### PR TITLE
VDX-163 - verifyCredential & verifyPresentation events

### PR DESCRIPTION
**Pull request by sanderPostma**

### CODE REVIEW

**Comment by nklomp** [comment]
@sanderPostma Please update to latest SSI-SDK code and fix build issue with this branch

**Comment by sanderPostma** [comment]
> @sanderPostma Please update to latest SSI-SDK code and fix build issue with this branch

Latest of the develop branch? Or newer like VDX-165?
the develop branch had import issues like "VerifiablePresentationWithLocation" and "PresentationLocation" which do not exists in did-auth-siop

**Comment by nklomp** [comment]
165 indeed

**Comment by sanderPostma** [comment]
Fixed. The problem was that the BBS jsonld.verify does not return result.presentationResult.results, only one root result.

**Review by nklomp — APPROVED** [review]
LGTM

**Pull request merged**
